version: '2'

services:
  postgresql:
    image: docker.io/bitnami/postgresql:14
    ports:
      - '5432:5432'
    volumes:
      - 'postgresql_data:/bitnami/postgresql'
    environment:
      - POSTGRESQL_DATABASE=dev
      - POSTGRESQL_PASSWORD=qwe123

volumes:
  postgresql_data:
    driver: local
